7.x 1.2 beta
tributemedia/better_mm pull request #24
Opened 2018-02-25 04:51 UTC by AntonioXIII

This branch addresses the following:

- BMM block HTML is no longer generated in three separate places (which creates a maintenance nightmare). The block HTML is now generated with one function in a new helpers.php file.
- Menu items can now be pointed at <front> and have a dropdown.
- Multiple menu items can now be pointed at the same link, so long as they don't have the same title.

@skenley Please verify through your own testing before merging. I have already undergone my own tests of the new version, and everything passed.

2018-02-28 17:54 UTC, skenley requested changes
bmm_menu_items_settings, seems to be only updating with the save of the BMM settings form. Need to make sure it's updated on save of menu item form, and probably the node save.

If a menu item has the same title AND path as another item the children of the first appearing item is given to the second appearing item.

2018-02-28 18:17 UTC, AntonioXIII commented
Steve tested on: https://dashboard.pantheon.io/sites/bdf5c670-2a08-4b02-86a4-85691e481772#bmm-test

2018-03-05 02:12 UTC, AntonioXIII commented
@skenley I have fixed the issues you found in your testing. This is now ready for testing again.

2018-03-13 17:00 UTC, skenley approved these changes

2018-03-13 17:01 UTC, merged